- platform: integration
  name: Total energy consumed
  source: sensor.power_meter_power_load_consumed

- platform: integration
  name: Total energy cost
  source: sensor.total_power_cost
- platform: integration
  name: Total energy cost savings
  source: sensor.total_power_cost_savings
- platform: statistics
  name: Total energy cost over last 7 days
  entity_id: sensor.total_energy_cost
  state_characteristic: change
  max_age:
    days: 7
- platform: statistics
  name: Total energy cost over last 30 days
  entity_id: sensor.total_energy_cost
  state_characteristic: change
  max_age:
    days: 30
- platform: statistics
  name: Total energy cost over last 365 days
  entity_id: sensor.total_energy_cost
  state_characteristic: change
  max_age:
    days: 365

- platform: integration
  name: Lights energy cost
  source: sensor.lights_power_cost
  max_sub_interval:
    minutes: 1
- platform: integration
  name: Lights energy cost savings
  source: sensor.lights_power_cost_savings
  max_sub_interval:
    minutes: 1
- platform: statistics
  name: Lights energy cost over last 7 days
  entity_id: sensor.lights_energy_cost
  state_characteristic: change
  max_age:
    days: 7
- platform: statistics
  name: Lights energy cost over last 30 days
  entity_id: sensor.lights_energy_cost
  state_characteristic: change
  max_age:
    days: 30
- platform: statistics
  name: Lights energy cost over last 365 days
  entity_id: sensor.lights_energy_cost
  state_characteristic: change
  max_age:
    days: 365

- platform: integration
  name: Living room aircon energy cost
  source: sensor.living_room_aircon_power_cost
  max_sub_interval:
    minutes: 1
- platform: integration
  name: Living room aircon energy cost savings
  source: sensor.living_room_aircon_power_cost_savings
  max_sub_interval:
    minutes: 1
- platform: statistics
  name: Living room aircon energy cost over last 7 days
  entity_id: sensor.living_room_aircon_energy_cost
  state_characteristic: change
  max_age:
    days: 7
- platform: statistics
  name: Living room aircon energy cost over last 30 days
  entity_id: sensor.living_room_aircon_energy_cost
  state_characteristic: change
  max_age:
    days: 30
- platform: statistics
  name: Living room aircon energy cost over last 365 days
  entity_id: sensor.living_room_aircon_energy_cost
  state_characteristic: change
  max_age:
    days: 365

- platform: integration
  name: Dining room aircon energy cost
  source: sensor.dining_room_aircon_power_cost
  max_sub_interval:
    minutes: 1
- platform: integration
  name: Dining room aircon energy cost savings
  source: sensor.dining_room_aircon_power_cost_savings
  max_sub_interval:
    minutes: 1
- platform: statistics
  name: Dining room aircon energy cost over last 7 days
  entity_id: sensor.dining_room_aircon_energy_cost
  state_characteristic: change
  max_age:
    days: 7
- platform: statistics
  name: Dining room aircon energy cost over last 30 days
  entity_id: sensor.dining_room_aircon_energy_cost
  state_characteristic: change
  max_age:
    days: 30
- platform: statistics
  name: Dining room aircon energy cost over last 365 days
  entity_id: sensor.dining_room_aircon_energy_cost
  state_characteristic: change
  max_age:
    days: 365

- platform: integration
  name: Bedroom aircon energy cost
  source: sensor.bedroom_aircon_power_cost
  max_sub_interval:
    minutes: 1
- platform: integration
  name: Bedroom aircon energy cost savings
  source: sensor.bedroom_aircon_power_cost_savings
  max_sub_interval:
    minutes: 1
- platform: statistics
  name: Bedroom aircon energy cost over last 7 days
  entity_id: sensor.bedroom_aircon_energy_cost
  state_characteristic: change
  max_age:
    days: 7
- platform: statistics
  name: Bedroom aircon energy cost over last 30 days
  entity_id: sensor.bedroom_aircon_energy_cost
  state_characteristic: change
  max_age:
    days: 30
- platform: statistics
  name: Bedroom aircon energy cost over last 365 days
  entity_id: sensor.bedroom_aircon_energy_cost
  state_characteristic: change
  max_age:
    days: 365

- platform: integration
  name: Office heater energy cost
  source: sensor.office_heater_power_cost
  max_sub_interval:
    minutes: 1
- platform: integration
  name: Office heater energy cost savings
  source: sensor.office_heater_power_cost_savings
  max_sub_interval:
    minutes: 1
- platform: statistics
  name: Office heater energy cost over last 7 days
  entity_id: sensor.office_heater_energy_cost
  state_characteristic: change
  max_age:
    days: 7
- platform: statistics
  name: Office heater energy cost over last 30 days
  entity_id: sensor.office_heater_energy_cost
  state_characteristic: change
  max_age:
    days: 30
- platform: statistics
  name: Office heater energy cost over last 365 days
  entity_id: sensor.office_heater_energy_cost
  state_characteristic: change
  max_age:
    days: 365

- platform: integration
  name: Nursery heater energy cost
  source: sensor.nursery_heater_power_cost
  max_sub_interval:
    minutes: 1
- platform: integration
  name: Nursery heater energy cost savings
  source: sensor.nursery_heater_power_cost_savings
  max_sub_interval:
    minutes: 1
- platform: statistics
  name: Nursery heater energy cost over last 7 days
  entity_id: sensor.nursery_heater_energy_cost
  state_characteristic: change
  max_age:
    days: 7
- platform: statistics
  name: Nursery heater energy cost over last 30 days
  entity_id: sensor.nursery_heater_energy_cost
  state_characteristic: change
  max_age:
    days: 30
- platform: statistics
  name: Nursery heater energy cost over last 365 days
  entity_id: sensor.nursery_heater_energy_cost
  state_characteristic: change
  max_age:
    days: 365

- platform: integration
  name: Fans energy cost
  source: sensor.fans_power_cost
  max_sub_interval:
    minutes: 1
- platform: integration
  name: Fans energy cost savings
  source: sensor.fans_power_cost_savings
  max_sub_interval:
    minutes: 1
- platform: statistics
  name: Fans energy cost over last 7 days
  entity_id: sensor.fans_energy_cost
  state_characteristic: change
  max_age:
    days: 7
- platform: statistics
  name: Fans energy cost over last 30 days
  entity_id: sensor.fans_energy_cost
  state_characteristic: change
  max_age:
    days: 30
- platform: statistics
  name: Fans energy cost over last 365 days
  entity_id: sensor.fans_energy_cost
  state_characteristic: change
  max_age:
    days: 365

- platform: integration
  name: Humidifiers energy cost
  source: sensor.humidifiers_power_cost
  max_sub_interval:
    minutes: 1
- platform: integration
  name: Humidifiers energy cost savings
  source: sensor.humidifiers_power_cost_savings
  max_sub_interval:
    minutes: 1
- platform: statistics
  name: Humidifiers energy cost over last 7 days
  entity_id: sensor.humidifiers_energy_cost
  state_characteristic: change
  max_age:
    days: 7
- platform: statistics
  name: Humidifiers energy cost over last 30 days
  entity_id: sensor.humidifiers_energy_cost
  state_characteristic: change
  max_age:
    days: 30
- platform: statistics
  name: Humidifiers energy cost over last 365 days
  entity_id: sensor.humidifiers_energy_cost
  state_characteristic: change
  max_age:
    days: 365

- platform: integration
  name: Kitchen appliances energy cost
  source: sensor.kitchen_appliances_power_cost
  max_sub_interval:
    minutes: 1
- platform: integration
  name: Kitchen appliances energy cost savings
  source: sensor.kitchen_appliances_power_cost_savings
  max_sub_interval:
    minutes: 1
- platform: statistics
  name: Kitchen appliances energy cost over last 7 days
  entity_id: sensor.kitchen_appliances_energy_cost
  state_characteristic: change
  max_age:
    days: 7
- platform: statistics
  name: Kitchen appliances energy cost over last 30 days
  entity_id: sensor.kitchen_appliances_energy_cost
  state_characteristic: change
  max_age:
    days: 30
- platform: statistics
  name: Kitchen appliances energy cost over last 365 days
  entity_id: sensor.kitchen_appliances_energy_cost
  state_characteristic: change
  max_age:
    days: 365

- platform: integration
  name: Dishwasher energy cost
  source: sensor.dishwasher_power_cost
  max_sub_interval:
    minutes: 1
- platform: integration
  name: Dishwasher energy cost savings
  source: sensor.dishwasher_power_cost_savings
  max_sub_interval:
    minutes: 1
- platform: statistics
  name: Dishwasher energy cost over last 7 days
  entity_id: sensor.dishwasher_energy_cost
  state_characteristic: change
  max_age:
    days: 7
- platform: statistics
  name: Dishwasher energy cost over last 30 days
  entity_id: sensor.dishwasher_energy_cost
  state_characteristic: change
  max_age:
    days: 30
- platform: statistics
  name: Dishwasher energy cost over last 365 days
  entity_id: sensor.dishwasher_energy_cost
  state_characteristic: change
  max_age:
    days: 365

- platform: integration
  name: Fridge energy cost
  source: sensor.fridge_power_cost
  max_sub_interval:
    minutes: 1
- platform: integration
  name: Fridge energy cost savings
  source: sensor.fridge_power_cost_savings
  max_sub_interval:
    minutes: 1
- platform: statistics
  name: Fridge energy cost over last 7 days
  entity_id: sensor.fridge_energy_cost
  state_characteristic: change
  max_age:
    days: 7
- platform: statistics
  name: Fridge energy cost over last 30 days
  entity_id: sensor.fridge_energy_cost
  state_characteristic: change
  max_age:
    days: 30
- platform: statistics
  name: Fridge energy cost over last 365 days
  entity_id: sensor.fridge_energy_cost
  state_characteristic: change
  max_age:
    days: 365

- platform: integration
  name: Freezer, mini fridge, routers energy cost
  source: sensor.freezer_mini_fridge_routers_power_cost
  max_sub_interval:
    minutes: 1
- platform: integration
  name: Freezer, mini fridge, routers energy cost savings
  source: sensor.freezer_mini_fridge_routers_power_cost_savings
  max_sub_interval:
    minutes: 1
- platform: statistics
  name: Freezer, mini fridge, routers energy cost over last 7 days
  entity_id: sensor.freezer_mini_fridge_routers_energy_cost
  state_characteristic: change
  max_age:
    days: 7
- platform: statistics
  name: Freezer, mini fridge, routers energy cost over last 30 days
  entity_id: sensor.freezer_mini_fridge_routers_energy_cost
  state_characteristic: change
  max_age:
    days: 30
- platform: statistics
  name: Freezer, mini fridge, routers energy cost over last 365 days
  entity_id: sensor.freezer_mini_fridge_routers_energy_cost
  state_characteristic: change
  max_age:
    days: 365

- platform: integration
  name: Washer energy cost
  source: sensor.washer_power_cost
  max_sub_interval:
    minutes: 1
- platform: integration
  name: Washer energy cost savings
  source: sensor.washer_power_cost_savings
  max_sub_interval:
    minutes: 1
- platform: statistics
  name: Washer energy cost over last 7 days
  entity_id: sensor.washer_energy_cost
  state_characteristic: change
  max_age:
    days: 7
- platform: statistics
  name: Washer energy cost over last 30 days
  entity_id: sensor.washer_energy_cost
  state_characteristic: change
  max_age:
    days: 30
- platform: statistics
  name: Washer energy cost over last 365 days
  entity_id: sensor.washer_energy_cost
  state_characteristic: change
  max_age:
    days: 365

- platform: integration
  name: Dryer energy cost
  source: sensor.dryer_power_cost
  max_sub_interval:
    minutes: 1
- platform: integration
  name: Dryer energy cost savings
  source: sensor.dryer_power_cost_savings
  max_sub_interval:
    minutes: 1
- platform: statistics
  name: Dryer energy cost over last 7 days
  entity_id: sensor.dryer_energy_cost
  state_characteristic: change
  max_age:
    days: 7
- platform: statistics
  name: Dryer energy cost over last 30 days
  entity_id: sensor.dryer_energy_cost
  state_characteristic: change
  max_age:
    days: 30
- platform: statistics
  name: Dryer energy cost over last 365 days
  entity_id: sensor.dryer_energy_cost
  state_characteristic: change
  max_age:
    days: 365

- platform: integration
  name: TV, speakers, PC, Home Assistant, router relay, security hub energy cost
  source: sensor.tv_speakers_pc_home_assistant_router_relay_security_hub_power_cost
  max_sub_interval:
    minutes: 1
- platform: integration
  name: TV, speakers, PC, Home Assistant, router relay, security hub energy cost savings
  source: sensor.tv_speakers_pc_home_assistant_router_relay_security_hub_power_cost_savings
  max_sub_interval:
    minutes: 1
- platform: statistics
  name: TV, speakers, PC, Home Assistant, router relay, security hub energy cost over last 7 days
  entity_id: sensor.tv_speakers_pc_home_assistant_router_relay_security_hub_energy_cost
  state_characteristic: change
  max_age:
    days: 7
- platform: statistics
  name: TV, speakers, PC, Home Assistant, router relay, security hub energy cost over last 30 days
  entity_id: sensor.tv_speakers_pc_home_assistant_router_relay_security_hub_energy_cost
  state_characteristic: change
  max_age:
    days: 30
- platform: statistics
  name: TV, speakers, PC, Home Assistant, router relay, security hub energy cost over last 365 days
  entity_id: sensor.tv_speakers_pc_home_assistant_router_relay_security_hub_energy_cost
  state_characteristic: change
  max_age:
    days: 365

- platform: integration
  name: Water heater, oven & stove, guest suite, garage, all other energy cost
  source: sensor.water_heater_oven_stove_guest_suite_garage_all_other_power_cost
  max_sub_interval:
    minutes: 1
- platform: integration
  name: Water heater, oven & stove, guest suite, garage, all other energy cost savings
  source: sensor.water_heater_oven_stove_guest_suite_garage_all_other_power_cost_savings
  max_sub_interval:
    minutes: 1
- platform: statistics
  name: Water heater, oven & stove, guest suite, garage, all other energy cost over last 7 days
  entity_id: sensor.water_heater_oven_stove_guest_suite_garage_all_other_energy_cost
  state_characteristic: change
  max_age:
    days: 7
- platform: statistics
  name: Water heater, oven & stove, guest suite, garage, all other energy cost over last 30 days
  entity_id: sensor.water_heater_oven_stove_guest_suite_garage_all_other_energy_cost
  state_characteristic: change
  max_age:
    days: 30
- platform: statistics
  name: Water heater, oven & stove, guest suite, garage, all other energy cost over last 365 days
  entity_id: sensor.water_heater_oven_stove_guest_suite_garage_all_other_energy_cost
  state_characteristic: change
  max_age:
    days: 365

- platform: integration
  name: Office desk, computer & monitor, cooler, fish tank energy cost
  source: sensor.office_desk_computer_monitor_cooler_fish_tank_power_cost
  max_sub_interval:
    minutes: 1
- platform: integration
  name: Office desk, computer & monitor, cooler, fish tank energy cost savings
  source: sensor.office_desk_computer_monitor_cooler_fish_tank_power_cost_savings
  max_sub_interval:
    minutes: 1
- platform: statistics
  name: Office desk, computer & monitor, cooler, fish tank energy cost over last 7 days
  entity_id: sensor.office_desk_computer_monitor_cooler_fish_tank_energy_cost
  state_characteristic: change
  max_age:
    days: 7
- platform: statistics
  name: Office desk, computer & monitor, cooler, fish tank energy cost over last 30 days
  entity_id: sensor.office_desk_computer_monitor_cooler_fish_tank_energy_cost
  state_characteristic: change
  max_age:
    days: 30
- platform: statistics
  name: Office desk, computer & monitor, cooler, fish tank energy cost over last 365 days
  entity_id: sensor.office_desk_computer_monitor_cooler_fish_tank_energy_cost
  state_characteristic: change
  max_age:
    days: 365

- platform: integration
  name: Phone chargers energy cost
  source: sensor.phone_chargers_power_cost
  max_sub_interval:
    minutes: 1
- platform: integration
  name: Phone chargers energy cost savings
  source: sensor.phone_chargers_power_cost_savings
  max_sub_interval:
    minutes: 1
- platform: statistics
  name: Phone chargers energy cost over last 7 days
  entity_id: sensor.phone_chargers_energy_cost
  state_characteristic: change
  max_age:
    days: 7
- platform: statistics
  name: Phone chargers energy cost over last 30 days
  entity_id: sensor.phone_chargers_energy_cost
  state_characteristic: change
  max_age:
    days: 30
- platform: statistics
  name: Phone chargers energy cost over last 365 days
  entity_id: sensor.phone_chargers_energy_cost
  state_characteristic: change
  max_age:
    days: 365

- platform: integration
  name: Sensors energy cost
  source: sensor.sensors_power_cost
  max_sub_interval:
    minutes: 1
- platform: integration
  name: Sensors energy cost savings
  source: sensor.sensors_power_cost_savings
  max_sub_interval:
    minutes: 1
- platform: statistics
  name: Sensors energy cost over last 7 days
  entity_id: sensor.sensors_energy_cost
  state_characteristic: change
  max_age:
    days: 7
- platform: statistics
  name: Sensors energy cost over last 30 days
  entity_id: sensor.sensors_energy_cost
  state_characteristic: change
  max_age:
    days: 30
- platform: statistics
  name: Sensors energy cost over last 365 days
  entity_id: sensor.sensors_energy_cost
  state_characteristic: change
  max_age:
    days: 365

- platform: integration
  name: Paludarium, picture frame, camera energy cost
  source: sensor.paludarium_picture_frame_camera_power_cost
  max_sub_interval:
    minutes: 1
- platform: integration
  name: Paludarium, picture frame, camera energy cost savings
  source: sensor.paludarium_picture_frame_camera_power_cost_savings
  max_sub_interval:
    minutes: 1
- platform: statistics
  name: Paludarium, picture frame, camera energy cost over last 7 days
  entity_id: sensor.paludarium_picture_frame_camera_energy_cost
  state_characteristic: change
  max_age:
    days: 7
- platform: statistics
  name: Paludarium, picture frame, camera energy cost over last 30 days
  entity_id: sensor.paludarium_picture_frame_camera_energy_cost
  state_characteristic: change
  max_age:
    days: 30
- platform: statistics
  name: Paludarium, picture frame, camera energy cost over last 365 days
  entity_id: sensor.paludarium_picture_frame_camera_energy_cost
  state_characteristic: change
  max_age:
    days: 365

- platform: integration
  name: Standby energy cost
  source: sensor.standby_power_cost
  max_sub_interval:
    minutes: 1
- platform: integration
  name: Standby energy cost savings
  source: sensor.standby_power_cost_savings
  max_sub_interval:
    minutes: 1
- platform: statistics
  name: Standby energy cost over last 7 days
  entity_id: sensor.standby_energy_cost
  state_characteristic: change
  max_age:
    days: 7
- platform: statistics
  name: Standby energy cost over last 30 days
  entity_id: sensor.standby_energy_cost
  state_characteristic: change
  max_age:
    days: 30
- platform: statistics
  name: Standby energy cost over last 365 days
  entity_id: sensor.standby_energy_cost
  state_characteristic: change
  max_age:
    days: 365

- platform: derivative
  name: Dan's phone charger power
  source: sensor.dan_s_phone_charger_energy
  unit: kW
  time_window: "00:15:00"
