- id: '2175874343931'
  alias: 'Start HomeKit'
  trigger:
  - event_type: zwave.network_ready
    platform: event
  - event_type: zwave.network_complete
    platform: event
  - event_type: zwave.network_complete_some_dead
    platform: event
  action:
  - service: notify.notify
    data:
      message: 'Home Assistant ready'
  - delay: 00:01 # TODO: remove?
  - service: homekit.start
- id: '4901248580234'
  alias: Notify when someone leaves home
  trigger:
    platform: zone
    event: leave
    zone: zone.home
    entity_id:
    - device_tracker.iphone
    - device_tracker.rachel_s_phone # TODO: update with Google Maps integration
  action:
    service: notify.notify
    data:
      message: 'Someone left the house'