- id: '2175874343931'
  alias: 'Start HomeKit'
  trigger:
  - event_type: zwave.network_ready
    platform: event
  - event_type: zwave.network_complete
    platform: event
  - event_type: zwave.network_complete_some_dead
    platform: event
  action:
  - service: notify.notify
    data:
      message: 'Home Assistant ready'
  - delay: 00:01 # TODO: remove?
  - service: homekit.start
