# Entities
counter: !include ./configuration/counters.yaml
group: !include ./configuration/groups.yaml
homeassistant: !include ./configuration/customize.yaml
input_boolean: !include ./configuration/inputs/boolean.yaml
input_datetime: !include ./configuration/inputs/datetime.yaml
input_number: !include ./configuration/inputs/number.yaml
input_select: !include ./configuration/inputs/select.yaml
sensor: !include ./configuration/sensors/apparent-temperature.yaml
template:
  binary_sensor: !include ./configuration/sensors/binary.yaml
  sensor: !include_dir_merge_list ./configuration/sensors/sensors/

# System
automation: !include ./configuration/automations.yaml
config:
frontend:
history:
homeassistant_alerts:
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: true
  login_attempts_threshold: 10
ifttt:
  key: !secret ifttt_key
logbook:
mobile_app:
my:
network:
person:
sun:
system_health:
wake_on_lan:
zeroconf:
