automation:
  - alias: Turn TV On
    trigger:
      - platform: webostv.turn_on
        entity_id: media_player.tv
    action:
      - service: wake_on_lan.send_magic_packet
        data:
          mac: !secret tv_mac

config:

counter:
  warnings:
    name: Warnings
    restore: false
  errors:
    name: Errors
    restore: false

frontend:

group: !include groups.yaml

history:

homeassistant:
  customize: !include customize.yaml

homeassistant_alerts:

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: true
  login_attempts_threshold: 10

ifttt:
  key: !secret ifttt_key

input_boolean:
  custom_lighting:
    name: Custom lighting
    icon: mdi:knob
  climate_control:
    name: Automatic climate control
    icon: mdi:home-thermometer
  aircon:
    name: Aircon
    icon: mdi:air-conditioner
  pets_home_alone:
    name: Pets home alone
    icon: mdi:dog-side
  development_mode:
    name: Development Mode
    icon: mdi:dev-to

input_datetime:
  morning_time:
    name: Morning time
    has_time: true
    icon: mdi:alarm
  bed_time:
    name: Bed time
    has_time: true
    icon: mdi:bed-clock
  circadian_end_time:
    name: End time
    has_time: true
    icon: mdi:clock-end

input_number:
  cooling_target_temperature:
    name: Cool down to
    min: 15
    max: 25
    unit_of_measurement: °C
    mode: box
    icon: mdi:thermometer-chevron-down
  heating_target_temperature:
    name: Heat up to
    min: 15
    max: 25
    unit_of_measurement: °C
    mode: box
    icon: mdi:thermometer-chevron-up
  sleep_cooling_target_temperature:
    name: Cool down to
    min: 15
    max: 25
    unit_of_measurement: °C
    mode: box
    icon: mdi:thermometer-chevron-down
  sleep_heating_target_temperature:
    name: Heat up to
    min: 15
    max: 25
    unit_of_measurement: °C
    mode: box
    icon: mdi:thermometer-chevron-up
  high_temperature_trigger:
    name: Cool when above
    min: 20
    max: 40
    step: 0.5
    unit_of_measurement: °C
    mode: box
    icon: mdi:thermometer-high
  low_temperature_trigger:
    name: Heat when below
    min: 0
    max: 20
    step: 0.5
    unit_of_measurement: °C
    mode: box
    icon: mdi:thermometer-low
  sleep_high_temperature_trigger:
    name: Cool when above
    min: 20
    max: 40
    step: 0.5
    unit_of_measurement: °C
    mode: box
    icon: mdi:thermometer-high
  sleep_low_temperature_trigger:
    name: Heat when below
    min: 0
    max: 20
    step: 0.5
    unit_of_measurement: °C
    mode: box
    icon: mdi:thermometer-low
  aircon_door_check_delay:
    name: Delay
    min: 1
    max: 10
    step: 1
    unit_of_measurement: min
    mode: box
    icon: mdi:timer
  initial_circadian_brightness:
    name: Initial brightness
    min: 25
    max: 255
    step: 10
    icon: mdi:lightbulb-on-80
  initial_circadian_kelvin:
    name: Initial kelvin
    min: 2000
    max: 4500
    step: 250
    icon: mdi:lightbulb-variant
  final_circadian_brightness:
    name: Final brightness
    min: 25
    max: 255
    step: 10
    icon: mdi:lightbulb-on-40
  final_circadian_kelvin:
    name: Final kelvin
    min: 2000
    max: 4500
    step: 250
    icon: mdi:lightbulb-variant-outline
  circadian_initial_sunset_offset:
    name: Initial sunset offset
    min: -3
    max: 3
    step: 0.5
    mode: box
    icon: mdi:weather-sunset-down
  night_motion_brightness:
    name: Motion brightness
    min: 25
    max: 255
    step: 10
    icon: mdi:lightbulb-on-80
  night_motion_kelvin:
    name: Motion kelvin
    min: 2000
    max: 4500
    step: 250
    icon: mdi:lightbulb-variant
  night_transition_period:
    name: Transition period
    min: 30
    max: 300
    step: 15
    icon: mdi:timer-cog
  night_vacating_delay:
    name: Vacating delay
    min: 0
    max: 300
    step: 15
    icon: mdi:timer
  tv_brightness:
    name: Brightness
    min: 25
    max: 255
    step: 10
    icon: mdi:lightbulb-on-40
  tv_motion_brightness:
    name: Motion brightness
    min: 25
    max: 255
    step: 10
    icon: mdi:lightbulb-on-80
  tv_kelvin:
    name: Kelvin
    min: 2000
    max: 4500
    step: 250
    icon: mdi:lightbulb-variant
  tv_transition_period:
    name: Transition period
    min: 30
    max: 300
    step: 15
    icon: mdi:timer-cog
  tv_vacating_delay:
    name: Vacating delay
    min: 0
    max: 300
    step: 15
    icon: mdi:timer
  sleep_motion_brightness:
    name: Motion brightness
    min: 25
    max: 255
    step: 10
    icon: mdi:lightbulb-on-80
  sleep_motion_kelvin:
    name: Motion kelvin
    min: 2000
    max: 4500
    step: 250
    icon: mdi:lightbulb-variant
  sleep_transition_period:
    name: Transition period
    min: 30
    max: 300
    step: 15
    icon: mdi:timer-cog
  sleep_vacating_delay:
    name: Vacating delay
    min: 0
    max: 300
    step: 15
    icon: mdi:timer
  morning_brightness:
    name: Brightness
    min: 25
    max: 255
    step: 10
    icon: mdi:lightbulb-on-80
  morning_kelvin:
    name: Kelvin
    min: 2000
    max: 4500
    step: 250
    icon: mdi:lightbulb-variant
  morning_vacating_delay:
    name: Vacating delay
    min: 0
    max: 300
    step: 15
    icon: mdi:timer
  office_vacating_delay:
    name: Office
    min: 0
    max: 300
    step: 15
    icon: mdi:timer
  bedroom_vacating_delay:
    name: Bedroom
    min: 0
    max: 300
    step: 15
    icon: mdi:timer

input_select:
  scene:
    name: Scene
    options:
      - Custom
      - Day
      - Night
      - Bright
      - Sleep
      - Morning
      - TV
      - Away (Day)
      - Away (Night)
    icon: mdi:home-lightbulb

logbook:

map:

mobile_app:

my:

network:

person:

sun:

system_health:

template:
  - binary_sensor:
      - name: Any climate control
        state: "{{ states('input_boolean.aircon') == 'on' or states('input_boolean.climate_control') == 'on' }}"
      - name: Display day card
        state: "{{ states('input_select.scene') != 'Sleep' and today_at('00:00') + timedelta(seconds=state_attr('input_datetime.bed_time', 'timestamp')) > now() }}"
  - sensor:
      - name: Inside apparent temperature
        unit_of_measurement: °C
        state: "{{ None }}"
        state_class: measurement
      - name: Nest Protect entryway battery level
        state: "{{ 90 if states('binary_sensor.nest_protect_entryway_battery_health') == 'off' else 10 }}"
        unit_of_measurement: "%"
        state_class: measurement
      - name: Nest Protect living room battery level
        state: "{{ 90 if states('binary_sensor.nest_protect_living_room_battery_health') == 'off' else 10 }}"
        unit_of_measurement: "%"
        state_class: measurement
      - name: Nest Protect garage battery level
        state: "{{ 90 if states('binary_sensor.nest_protect_garage_battery_health') == 'off' else 10 }}"
        unit_of_measurement: "%"
        state_class: measurement

wake_on_lan:

zeroconf:
