# Entities
binary_sensor: !include_dir_merge_list ./configuration/binary_sensors/
counter: !include ./configuration/counters.yaml
group: !include ./configuration/groups.yaml
homeassistant: !include ./configuration/customize.yaml
input_boolean: !include ./configuration/inputs/boolean.yaml
input_datetime: !include ./configuration/inputs/datetime.yaml
input_number: !include ./configuration/inputs/number.yaml
input_select: !include ./configuration/inputs/select.yaml
powercalc: !include ./configuration/powercalc.yaml
sensor: !include_dir_merge_list ./configuration/sensors/
switch: !include ./configuration/switches.yaml
template:
  binary_sensor: !include_dir_merge_list ./configuration/templates/binary/
  sensor: !include_dir_merge_list ./configuration/templates/sensors/
utility_meter: !include ./configuration/utility_meters.yaml

# System
automation: !include ./configuration/automations.yaml
config:
energy:
frontend:
  extra_module_url:
    - /local/community/bar-card/bar-card.js
    - /local/community/lovelace-auto-entities/auto-entities.js
    - /local/community/lovelace-card-mod/card-mod.js
    - /local/community/lovelace-multiple-entity-row/multiple-entity-row.js
    - /local/community/power-flow-card-plus/power-flow-card-plus.js
history:
homeassistant_alerts:
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: true
  login_attempts_threshold: 10
ifttt:
  key: !secret ifttt_key
logbook:
mobile_app:
my:
network:
person:
sun:
system_health:
wake_on_lan:
zeroconf:
