# Entities
counter: !include ./configuration/counters.yaml
group: !include ./configuration/groups.yaml
homeassistant: !include ./configuration/customize.yaml
input_boolean: !include ./configuration/inputs/booleans.yaml
input_datetime: !include ./configuration/inputs/datetimes.yaml
input_number: !include ./configuration/inputs/numbers.yaml
input_select: !include ./configuration/inputs/selects.yaml
template: !include ./configuration/sensors.yaml

# System
automation: !include ./configuration/automations.yaml
config:
frontend:
history:
homeassistant_alerts:
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: true
  login_attempts_threshold: 10
ifttt:
  key: !secret ifttt_key
logbook:
mobile_app:
my:
network:
person:
sun:
system_health:
wake_on_lan:
zeroconf:
