automation:
  - alias: Turn TV on if not already on
    description: "Required to turn the TV on from Home Assistant - sends a wake on lan magic packet"
    trigger:
      - platform: webostv.turn_on
        entity_id: media_player.tv
    action:
      - service: wake_on_lan.send_magic_packet
        data:
          mac: !secret tv_mac

config:

counter:
  warnings:
    name: Warnings
    restore: false
  errors:
    name: Errors
    restore: false

frontend:

group: !include groups.yaml

history:

homeassistant:
  customize: !include customize.yaml

homeassistant_alerts:

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: true
  login_attempts_threshold: 10

ifttt:
  key: !secret ifttt_key

input_boolean:
  custom_lighting:
    name: Custom lighting
    icon: mdi:knob
  climate_control:
    name: Automatic climate control
    icon: mdi:home-thermometer
  aircon:
    name: Aircon
    icon: mdi:air-conditioner
  pets_home_alone:
    name: Pets home alone
    icon: mdi:dog-side
  development_mode:
    name: Development Mode
    icon: mdi:dev-to

input_datetime:
  morning_time:
    name: Morning time
    has_time: true
    icon: mdi:alarm
  bed_time:
    name: Bed time
    has_time: true
    icon: mdi:bed-clock
  circadian_end_time:
    name: End time
    has_time: true
    icon: mdi:clock-end

input_number:
  cooling_target_temperature:
    name: Cool down to
    min: 15
    max: 25
    unit_of_measurement: °C
    mode: box
    icon: mdi:thermometer-chevron-down
  heating_target_temperature:
    name: Heat up to
    min: 15
    max: 25
    unit_of_measurement: °C
    mode: box
    icon: mdi:thermometer-chevron-up
  sleep_cooling_target_temperature:
    name: Cool down to
    min: 15
    max: 25
    unit_of_measurement: °C
    mode: box
    icon: mdi:thermometer-chevron-down
  sleep_heating_target_temperature:
    name: Heat up to
    min: 15
    max: 25
    unit_of_measurement: °C
    mode: box
    icon: mdi:thermometer-chevron-up
  high_temperature_aircon_trigger:
    name: Aircon cools once above
    min: 20
    max: 40
    step: 0.5
    unit_of_measurement: °C
    mode: box
    icon: mdi:thermometer-high
  low_temperature_aircon_trigger:
    name: Aircon heats once below
    min: 0
    max: 20
    step: 0.5
    unit_of_measurement: °C
    mode: box
    icon: mdi:thermometer-low
  sleep_high_temperature_aircon_trigger:
    name: Aircon cools once above
    min: 20
    max: 40
    step: 0.5
    unit_of_measurement: °C
    mode: box
    icon: mdi:thermometer-high
  sleep_low_temperature_aircon_trigger:
    name: Aircon heats once below
    min: 0
    max: 20
    step: 0.5
    unit_of_measurement: °C
    mode: box
    icon: mdi:thermometer-low
  aircon_door_check_delay:
    name: Aircon off if door open
    min: 1
    max: 10
    step: 1
    unit_of_measurement: min
    mode: box
    icon: mdi:timer
  fan_vacating_delay:
    name: Fan off if room empty
    min: 1
    max: 10
    step: 1
    unit_of_measurement: min
    mode: box
    icon: mdi:timer
  initial_circadian_brightness:
    name: Initial brightness
    min: 25
    max: 255
    step: 10
    icon: mdi:lightbulb-on-80
  initial_circadian_kelvin:
    name: Initial kelvin
    min: 2000
    max: 4500
    step: 250
    icon: mdi:lightbulb-variant
  final_circadian_brightness:
    name: Final brightness
    min: 25
    max: 255
    step: 10
    icon: mdi:lightbulb-on-40
  final_circadian_kelvin:
    name: Final kelvin
    min: 2000
    max: 4500
    step: 250
    icon: mdi:lightbulb-variant-outline
  circadian_initial_sunset_offset:
    name: Initial sunset offset
    min: -3
    max: 3
    step: 0.5
    mode: box
    icon: mdi:weather-sunset-down
  night_motion_brightness:
    name: Motion brightness
    min: 25
    max: 255
    step: 10
    icon: mdi:lightbulb-on-80
  night_motion_kelvin:
    name: Motion kelvin
    min: 2000
    max: 4500
    step: 250
    icon: mdi:lightbulb-variant
  night_transition_period:
    name: Transition period
    min: 30
    max: 300
    step: 15
    icon: mdi:timer-cog
  night_vacating_delay:
    name: Vacating delay
    min: 0
    max: 300
    step: 15
    icon: mdi:timer
  tv_brightness:
    name: Brightness
    min: 25
    max: 255
    step: 10
    icon: mdi:lightbulb-on-40
  tv_motion_brightness:
    name: Motion brightness
    min: 25
    max: 255
    step: 10
    icon: mdi:lightbulb-on-80
  tv_kelvin:
    name: Kelvin
    min: 2000
    max: 4500
    step: 250
    icon: mdi:lightbulb-variant
  tv_transition_period:
    name: Transition period
    min: 30
    max: 300
    step: 15
    icon: mdi:timer-cog
  tv_vacating_delay:
    name: Vacating delay
    min: 0
    max: 300
    step: 15
    icon: mdi:timer
  sleep_motion_brightness:
    name: Motion brightness
    min: 25
    max: 255
    step: 10
    icon: mdi:lightbulb-on-80
  sleep_motion_kelvin:
    name: Motion kelvin
    min: 2000
    max: 4500
    step: 250
    icon: mdi:lightbulb-variant
  sleep_transition_period:
    name: Transition period
    min: 30
    max: 300
    step: 15
    icon: mdi:timer-cog
  sleep_vacating_delay:
    name: Vacating delay
    min: 0
    max: 300
    step: 15
    icon: mdi:timer
  morning_brightness:
    name: Brightness
    min: 25
    max: 255
    step: 10
    icon: mdi:lightbulb-on-80
  morning_kelvin:
    name: Kelvin
    min: 2000
    max: 4500
    step: 250
    icon: mdi:lightbulb-variant
  morning_vacating_delay:
    name: Vacating delay
    min: 0
    max: 300
    step: 15
    icon: mdi:timer
  office_vacating_delay:
    name: Office
    min: 0
    max: 300
    step: 15
    icon: mdi:timer
  bedroom_vacating_delay:
    name: Bedroom
    min: 0
    max: 300
    step: 15
    icon: mdi:timer

input_select:
  scene:
    name: Scene
    options:
      - Custom
      - Day
      - Night
      - Bright
      - Sleep
      - Morning
      - TV
      - Away (Day)
      - Away (Night)
    icon: mdi:home-lightbulb

logbook:

mobile_app:

my:

network:

person:

sun:

system_health:

template:
  - binary_sensor:
      - name: Any climate control
        state: "{{ states('input_boolean.aircon') == 'on' or states('input_boolean.climate_control') == 'on' }}"
      - name: Display day card
        state: "{{ states('input_select.scene') != 'Sleep' and today_at('00:00') + timedelta(seconds=state_attr('input_datetime.bed_time', 'timestamp')) > now() }}"
      - name: Kitchen door motion
        state: "{{ now() - states.binary_sensor.kitchen_door.last_changed < timedelta(seconds=30) }}"
      - name: Daniels MacBook active at home
        state: "{{ states('binary_sensor.daniels_macbook_active') == 'on' and states('device_tracker.daniels_macbook') == 'home' }}"
      - name: TV playing
        state: "{{ states('sensor.webostvservice_play_state') == 'playing' }}"
      - name: Owlet attached
        state: "{{ states('binary_sensor.owlet_awake') != 'unknown' }}"
  - sensor:
      - name: Inside apparent temperature
        state: "{{ None }}"
        unit_of_measurement: "°C"
        state_class: measurement
      - name: Soil sensor vegetable garden sun battery level
        state: "{{ max(0, min(100, (100 * (float(states('sensor.soil_battery_voltage_vegetable_garden_sun')) - 1.0) / (1.6 - 1.0)) | round(2))) if has_value('sensor.soil_battery_voltage_vegetable_garden_sun') else 'unavailable' }}"
        unit_of_measurement: "%"
        state_class: measurement
      - name: Soil sensor vegetable garden shade battery level
        state: "{{ max(0, min(100, (100 * (float(states('sensor.soil_battery_voltage_vegetable_garden_shade')) - 1.0) / (1.6 - 1.0)) | round(2))) if has_value('sensor.soil_battery_voltage_vegetable_garden_shade') else 'unavailable' }}"
        unit_of_measurement: "%"
        state_class: measurement
      - name: Soil sensor front deck battery level
        state: "{{ max(0, min(100, (100 * (float(states('sensor.soil_battery_voltage_front_deck')) - 1.0) / (1.6 - 1.0)) | round(2))) if has_value('sensor.soil_battery_voltage_front_deck') else 'unavailable' }}"
        unit_of_measurement: "%"
        state_class: measurement
      - name: Soil sensor back deck battery level
        state: "{{ max(0, min(100, (100 * (float(states('sensor.soil_battery_voltage_back_deck')) - 1.0) / (1.6 - 1.0)) | round(2))) if has_value('sensor.soil_battery_voltage_back_deck') else 'unavailable' }}"
        unit_of_measurement: "%"
        state_class: measurement
      - name: Soil sensor carport pots battery level
        state: "{{ max(0, min(100, (100 * (float(states('sensor.soil_battery_voltage_carport_pots')) - 1.0) / (1.6 - 1.0)) | round(2))) if has_value('sensor.soil_battery_voltage_carport_pots') else 'unavailable' }}"
        unit_of_measurement: "%"
        state_class: measurement
      - name: Soil sensor dining room battery level
        state: "{{ max(0, min(100, (100 * (float(states('sensor.soil_battery_voltage_dining_room')) - 1.0) / (1.6 - 1.0)) | round(2))) if has_value('sensor.soil_battery_voltage_dining_room') else 'unavailable' }}"
        unit_of_measurement: "%"
        state_class: measurement
      - name: Soil sensor living room battery level
        state: "{{ max(0, min(100, (100 * (float(states('sensor.soil_battery_voltage_living_room')) - 1.0) / (1.6 - 1.0)) | round(2))) if has_value('sensor.soil_battery_voltage_living_room') else 'unavailable' }}"
        unit_of_measurement: "%"
        state_class: measurement
      - name: Soil sensor office battery level
        state: "{{ max(0, min(100, (100 * (float(states('sensor.soil_battery_voltage_office')) - 1.0) / (1.6 - 1.0)) | round(2))) if has_value('sensor.soil_battery_voltage_office') else 'unavailable' }}"
        unit_of_measurement: "%"
        state_class: measurement

wake_on_lan:

zeroconf:
