binary_sensor:
  - platform: template
    sensors:
      display_day_card:
        value_template: >
           {% set time = now() %}
           {{ states.input_select.scene.state != "Sleep" and states.input_datetime.bed_time.attributes.timestamp > (time - time.replace(hour=0,minute=0,second=0,microsecond=0)).total_seconds() }}

climate:
  platform: sensibo
  api_key: !secret sensibo_key

config:

counter:
  warnings:
  errors:

frontend:

group: !include groups.yaml

history:

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: true
  login_attempts_threshold: 10

ifttt:
  key: !secret ifttt_key

input_boolean:
  climate_control:
    name: "Automatic climate control"
  aircon:
    name: "Aircon"

input_datetime:
  morning_time:
    name: Morning time
    has_time: true
  bed_time:
    name: Bed time
    has_time: true
  circadian_end_time:
    name: End time
    has_time: true

input_number:
  cooling_target_temperature:
    name: "Cool down to"
    min: 15
    max: 25
    unit_of_measurement: "°C"
    mode: "box"
  heating_target_temperature:
    name: "Heat up to"
    min: 15
    max: 25
    unit_of_measurement: "°C"
    mode: "box"
  sleep_cooling_target_temperature:
    name: "Cool down to"
    min: 15
    max: 25
    unit_of_measurement: "°C"
    mode: "box"
  sleep_heating_target_temperature:
    name: "Heat up to"
    min: 15
    max: 25
    unit_of_measurement: "°C"
    mode: "box"
  high_temperature_trigger:
    name: "Cool when above"
    min: 20
    max: 40
    step: 0.5
    unit_of_measurement: "°C"
    mode: "box"
  low_temperature_trigger:
    name: "Heat when below"
    min: 0
    max: 20
    step: 0.5
    unit_of_measurement: "°C"
    mode: "box"
  sleep_high_temperature_trigger:
    name: "Cool when above"
    min: 20
    max: 40
    step: 0.5
    unit_of_measurement: "°C"
    mode: "box"
  sleep_low_temperature_trigger:
    name: "Heat when below"
    min: 0
    max: 20
    step: 0.5
    unit_of_measurement: "°C"
    mode: "box"
  aircon_door_check_delay:
    name: "Delay"
    min: 1
    max: 10
    step: 1
    unit_of_measurement: "min"
    mode: "box"
  initial_circadian_brightness:
    name: Initial brightness
    min: 25
    max: 255
    step: 10
  initial_circadian_kelvin:
    name: Initial kelvin
    min: 2000
    max: 4500
    step: 250
  final_circadian_brightness:
    name: Final brightness
    min: 25
    max: 255
    step: 10
  final_circadian_kelvin:
    name: Final kelvin
    min: 2000
    max: 4500
    step: 250
  circadian_initial_sunset_offset:
    name: Initial sunset offset
    min: -3
    max: 3
    step: 0.5
    mode: box
  night_motion_brightness:
    name: Motion brightness
    min: 25
    max: 255
    step: 10
  night_motion_kelvin:
    name: Motion kelvin
    min: 2000
    max: 4500
    step: 250
  night_transition_period:
    name: Transition period
    min: 30
    max: 300
    step: 15
  night_vacating_delay:
    name: Vacating delay
    min: 0
    max: 300
    step: 15
  tv_brightness:
    name: Brightness
    min: 25
    max: 255
    step: 10
  tv_motion_brightness:
    name: Motion brightness
    min: 25
    max: 255
    step: 10
  tv_kelvin:
    name: Kelvin
    min: 2000
    max: 4500
    step: 250
  tv_transition_period:
    name: Transition period
    min: 30
    max: 300
    step: 15
  tv_vacating_delay:
    name: Vacating delay
    min: 0
    max: 300
    step: 15
  sleep_motion_brightness:
    name: Motion brightness
    min: 25
    max: 255
    step: 10
  sleep_motion_kelvin:
    name: Motion kelvin
    min: 2000
    max: 4500
    step: 250
  sleep_transition_period:
    name: Transition period
    min: 30
    max: 300
    step: 15
  sleep_vacating_delay:
    name: Vacating delay
    min: 0
    max: 300
    step: 15
  morning_brightness:
    name: Brightness
    min: 25
    max: 255
    step: 10
  morning_kelvin:
    name: Kelvin
    min: 2000
    max: 4500
    step: 250
  morning_vacating_delay:
    name: Vacating delay
    min: 0
    max: 300
    step: 15
  office_vacating_delay:
    name: Office
    min: 0
    max: 300
    step: 15
  bedroom_vacating_delay:
    name: Bedroom
    min: 0
    max: 300
    step: 15

input_select:
  scene:
    name: Scene
    options:
    - Day
    - Night
    - Bright
    - Sleep
    - Morning
    - TV
    - Away (Day)
    - Away (Night)

logbook:

map:

media_player:

mobile_app:

person:

sensor:
- platform: darksky
  api_key: !secret darksky_key
  hourly_forecast:
  - 2
  - 4
  - 6
  - 8
  monitored_conditions:
  - apparent_temperature
- platform: template
  sensors:
    apparent_inside_temperature_numeric:
      friendly_name: "Apparent inside temperature"
      unit_of_measurement: "°C"
      value_template: "{{ states('sensor.apparent_inside_temperature') }}"
      icon_template: "mdi:thermometer"
    warnings_numeric:
      friendly_name: "Warnings"
      unit_of_measurement: "#"
      value_template: "{{ states('counter.warnings') }}"
    errors_numeric:
      friendly_name: "Errors"
      unit_of_measurement: "#"
      value_template: "{{ states('counter.errors') }}"
    any_climate_control:
      value_template: "{{ states('input_boolean.aircon') == 'on' or states('input_boolean.climate_control') == 'on' }}"

sun:

system_health:

tts:
  platform: google_translate

wake_on_lan:

webostv:
  host: 192.168.20.90
  name: "TV"
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: !secret tv_mac

zeroconf:
