cloud:
config:
energy:
frontend:
  themes: !include_dir_merge_named themes
history:
homeassistant:
  packages: !include_dir_named configuration
homeassistant_alerts:
http:
  ip_ban_enabled: true
  login_attempts_threshold: 10
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
ifttt:
  key: !secret ifttt_key
influxdb:
  host: a0d7b954-influxdb
  database: homeassistant
  username: homeassistant
  password: !secret influx_password
  max_retries: 3
  include:
    entity_globs:
      - sensor.*energy_cost
      - sensor.*energy_cost_savings
logbook:
mobile_app:
my:
network:
person:
recorder:
  exclude:
    entities:
      - sensor.weather_station_wind_speed
      - sensor.weather_station_wind_direction
      - sensor.electricity_cost_breakdown_dashboard_card
      - sensor.bubble_card_modules
    entity_globs:
      - sensor.*_presence_sensor_distance
      - sensor.*_presence_sensor_illuminance
sun:
system_health:
wake_on_lan:
zeroconf:
