badnest:
  issue_token: !secret badnest_token
  cookie: !secret badnest_cookie
  region: !secret badnest_region

climate:
  platform: sensibo
  api_key: !secret sensibo_key

config:

counter:
  warnings:
  errors:

device_tracker:
  platform: netgear
  password: !secret orbi_password
  consider_home: 0:05
  accesspoints: true # forces use of Orbi API v2, which is much faster

frontend:

group: !include groups.yaml

history:

homeassistant:
  customize: !include customize.yaml

http:
  base_url: !secret http_url
  server_port: !secret http_port
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: True
  login_attempts_threshold: 10

ifttt:
  key: !secret ifttt_key

input_boolean:
  climate_control:
    name: "Automatic climate control"
  aircon:
    name: "Aircon"

input_number:
  cooling_target_temperature:
    name: "Cool down to"
    min: 15
    max: 25
    step: 0.5
    unit_of_measurement: "°C"
    mode: "box"
  heating_target_temperature:
    name: "Heat up to"
    min: 15
    max: 25
    step: 0.5
    unit_of_measurement: "°C"
    mode: "box"
  high_temperature_trigger:
    name: "Cool when above"
    min: 20
    max: 40
    step: 0.5
    unit_of_measurement: "°C"
    mode: "box"
  low_temperature_trigger:
    name: "Heat when below"
    min: 0
    max: 20
    step: 0.5
    unit_of_measurement: "°C"
    mode: "box"
  night_trigger_reduction:
    name: "Reduce triggers at night by"
    min: -10
    max: 10
    step: 0.5
    unit_of_measurement: "°C"
    mode: "box"

input_select:
  scene:
    name: Scene
    options:
    - Day
    - Night
    - Sleep
    - Bright
    - TV
    - Away (Day)
    - Away (Night)

light:
- platform: wiz_light
  name: Hall
  host: 192.168.20.50
- platform: wiz_light
  name: TV Left
  host: 192.168.20.51
- platform: wiz_light
  name: TV Middle
  host: 192.168.20.52
- platform: wiz_light
  name: TV Right
  host: 192.168.20.53
- platform: wiz_light
  name: Kitchen
  host: 192.168.20.54
- platform: mqtt
  name: 'Office'
  command_topic: "light-office/cmnd/POWER"
  state_topic: "light-office/stat/RESULT"
  value_template: "{{ value_json.POWER }}"
  qos: 1
- platform: mqtt
  name: 'Bedroom'
  command_topic: "light-bedroom/cmnd/POWER"
  state_topic: "light-bedroom/stat/RESULT"
  value_template: "{{ value_json.POWER }}"
  qos: 1

logbook:

map:

mobile_app:

mqtt:
  broker: core-mosquitto
  username: !secret mqtt_username
  password: !secret mqtt_password

person:

sensor:
- platform: badnest
- platform: bom
  name: Weather
  station: !secret bom_station
  monitored_conditions:
  - apparent_t
- platform: darksky
  api_key: !secret darksky_key
  hourly_forecast:
  - 2
  - 4
  - 6
  - 8
  monitored_conditions:
  - apparent_temperature
- platform: template
  sensors:
    apparent_inside_temperature_numeric:
      friendly_name: "Apparent inside temperature"
      unit_of_measurement: "°C"
      value_template: "{{ states('sensor.apparent_inside_temperature') }}"
      icon_template: "mdi:thermometer"
    warnings_numeric:
      friendly_name: "Warnings"
      unit_of_measurement: "#"
      value_template: "{{ states('counter.warnings') }}"
    errors_numeric:
      friendly_name: "Errors"
      unit_of_measurement: "#"
      value_template: "{{ states('counter.errors') }}"
    any_climate_control:
      value_template: "{{ states('input_boolean.aircon') == 'on' or states('input_boolean.climate_control') == 'on' }}"

sun:

system_health:

tts:
  platform: google_translate

updater:
  include_used_components: True

zeroconf:

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_key
