config:
energy:
frontend:
  themes: !include_dir_merge_named themes
history:
homeassistant:
  packages: !include_dir_named configuration
homeassistant_alerts:
http:
  ip_ban_enabled: true
  login_attempts_threshold: 10
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
ifttt:
  key: !secret ifttt_key
influxdb:
  host: a0d7b954-influxdb
  database: homeassistant
  username: homeassistant
  password: !secret influx_password
  max_retries: 3
logbook:
mobile_app:
my:
network:
person:
sun:
system_health:
wake_on_lan:
zeroconf:
