badnest:
  issue_token: !secret badnest_token
  cookie: !secret badnest_cookie
  region: !secret badnest_region

climate:
  platform: sensibo
  api_key: !secret sensibo_key

config:

counter:
  warnings:
  errors:

device_tracker:
  platform: netgear
  password: !secret orbi_password
  consider_home: 0:05
  accesspoints: true # forces use of Orbi API v2, which is much faster

frontend:

group: !include groups.yaml

history:

homeassistant:
  customize: !include customize.yaml

http:
  base_url: !secret http_url
  server_port: !secret http_port
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: True
  login_attempts_threshold: 10

ifttt:
  key: !secret ifttt_key

input_boolean:
  climate_control:
    name: Automatic Climate Control
  aircon:
    name: Aircon

input_select:
  scene:
    name: Scene
    options:
    - Day
    - Night
    - Sleep
    - Bright
    - TV
    - Away (Day)
    - Away (Night)

light:
- platform: wiz_light
  name: Hall
  host: 192.168.20.25
- platform: wiz_light
  name: TV Left
  host: 192.168.20.24
- platform: wiz_light
  name: TV Middle
  host: 192.168.20.26
- platform: wiz_light
  name: TV Right
  host: 192.168.20.23
- platform: wiz_light
  name: Kitchen
  host: 192.168.20.22
- platform: mqtt
  name: 'Office'
  command_topic: "light-office/cmnd/POWER"
  state_topic: "light-office/stat/RESULT"
  value_template: "{{ value_json.POWER }}"
  qos: 1
- platform: mqtt
  name: 'Bedroom'
  command_topic: "light-bedroom/cmnd/POWER"
  state_topic: "light-bedroom/stat/RESULT"
  value_template: "{{ value_json.POWER }}"
  qos: 1

logbook:

map:

mobile_app:

mqtt:
  broker: core-mosquitto
  username: !secret mqtt_username
  password: !secret mqtt_password

person:

sensor:
- platform: badnest
- platform: bom
  name: Weather
  station: !secret bom_station
  monitored_conditions:
  - apparent_t
- platform: bom_forecast
  product_id: !secret bom_forecast_id
  name: Forecast
  forecast_days: 1
  monitored_conditions:
  - 'max'
  - 'min'

sun:

system_health:

tts:
  platform: google_translate

updater:
  include_used_components: True

zeroconf:

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_key
