title: Nest
views:
  - badges: []
    cards:
      - entities:
          - entity: input_select.scene
          - entity: input_boolean.climate_control
          - entity: input_boolean.aircon
        show_header_toggle: false
        title: Control
        type: entities
      - entities:
          - entity: light.kitchen
          - entity: group.main_lights
          - entity: light.bedroom
        show_icon: true
        show_name: true
        show_state: true
        title: Lights
        type: glance
      - type: markdown
        content: >-
          **Lighting** and climate settings are automatically adjusted between
          different scenes. You can select a preferred scene here or tell Siri/Google:

          - lights on/off

          - lights on bright

          - sleep time


          **Automatic climate control** will control all aircon units based on
          the temperature and scene. Aircon can also be manually turned on/off.
          These settings can be controlled by telling Siri/Google:

          - climate control on/off

          - aircon on/off
      - aspect_ratio: '2'
        default_zoom: 12
        entities:
          - entity: person.dan
          - entity: person.rachel
        type: map
      - entity: media_player.living_room
        type: media-control
      - entities:
          - entity: climate.bedroom
          - entity: climate.living_room
          - entity: climate.dining_room
          - entity: sensor.kitchen_multisensor_temperature
          - entity: sensor.multisensor_2_temperature
        hours_to_show: 80
        refresh_interval: 0
        title: Temperatures
        type: history-graph
      - entity: climate.bedroom
        type: thermostat
      - entity: climate.living_room
        type: thermostat
      - entity: climate.dining_room
        type: thermostat
    path: default_view
    title: Home
  - badges:
      - entity: binary_sensor.updater
      - entity: sensor.hacs
    cards:
      - entities:
          - entity: counter.warnings
          - entity: counter.errors
        hours_to_show: 80
        refresh_interval: 0
        type: history-graph
    path: system
    title: System
