title: Smart Nest
views:
  - badges: []
    cards:
      - entities:
          - entity: input_select.scene
          - entity: input_boolean.climate_control
          - entity: input_boolean.aircon
        show_header_toggle: false
        title: Control
        type: entities
      - card:
          entities:
            - entity: input_number.high_temperature_trigger
            - entity: input_number.low_temperature_trigger
          show_header_toggle: false
          title: Climate Control Triggers
          type: entities
        conditions:
          - entity: input_boolean.climate_control
            state: 'on'
          - entity: input_select.scene
            state_not: Sleep
        type: conditional
      - card:
          entities:
            - entity: input_number.sleep_high_temperature_trigger
            - entity: input_number.sleep_low_temperature_trigger
          show_header_toggle: false
          title: Climate Control Triggers
          type: entities
        conditions:
          - entity: input_boolean.climate_control
            state: 'on'
          - entity: input_select.scene
            state: Sleep
        type: conditional
      - card:
          entities:
            - entity: input_number.cooling_target_temperature
            - entity: input_number.heating_target_temperature
          show_header_toggle: false
          title: Aircon Temperatures
          type: entities
        conditions:
          - entity: sensor.any_climate_control
            state: 'True'
          - entity: input_select.scene
            state_not: Sleep
        type: conditional
      - card:
          entities:
            - entity: input_number.sleep_cooling_target_temperature
            - entity: input_number.sleep_heating_target_temperature
          show_header_toggle: false
          title: Aircon Temperatures
          type: entities
        conditions:
          - entity: sensor.any_climate_control
            state: 'True'
          - entity: input_select.scene
            state: Sleep
        type: conditional
      - entities:
          - entity: sensor.apparent_inside_temperature_numeric
            name: Inside
          - entity: sensor.dark_sky_apparent_temperature
            name: Outside
        show_name: true
        type: glance
      - cards:
          - entities:
              - entity: group.all_lights
              - entity: group.entryway_lights
              - entity: light.kitchen
              - entity: group.tv_lights
              - entity: group.dining_lights
              - entity: light.hall
              - entity: light.bedroom
              - entity: light.office
            show_icon: true
            show_name: true
            show_state: true
            title: Lights
            type: glance
          - content: >-
              To manually control lighting above, you should first set the scene
              to anything except "Night".
            type: markdown
        type: vertical-stack
      - content: >-
          **Lighting** and climate settings are automatically adjusted between
          different scenes. You can select a preferred scene here or tell
          Siri/Google:

          - lights on/off

          - lights on bright

          - sleep time


          **Automatic climate control** will control all aircon units based on
          the temperature and scene. **Aircon** can also be manually turned
          on/off. These settings can be controlled by telling Siri/Google:

          - climate control on/off

          - aircon on/off
        type: markdown
      - aspect_ratio: '2'
        dark_mode: false
        default_zoom: 12
        entities:
          - entity: person.dan
          - entity: person.rachel
        hours_to_show: 1
        type: map
      - entity: media_player.living_room
        type: media-control
      - entities:
          - entity: climate.bedroom
          - entity: climate.living_room
          - entity: climate.dining_room
          - entity: sensor.kitchen_multisensor_temperature
          - entity: sensor.multisensor_2_temperature
          - entity: sensor.dark_sky_apparent_temperature
          - entity: input_number.cooling_target_temperature
          - entity: input_number.heating_target_temperature
          - entity: input_number.high_temperature_trigger
          - entity: input_number.low_temperature_trigger
          - entity: sensor.apparent_inside_temperature_numeric
          - entity: sensor.bom_weather_feels_like_c
        hours_to_show: 72
        refresh_interval: 0
        title: Temperatures
        type: history-graph
      - cards:
          - entity: climate.living_room
            type: thermostat
          - entity: climate.dining_room
            type: thermostat
          - entity: climate.bedroom
            type: thermostat
          - content: >-
              To manually control the individual airconditioning units above,
              you should disable automatic climate control beforehand.
            type: markdown
        type: vertical-stack
    path: default_view
    title: Control & Status
  - badges:
      - entity: binary_sensor.updater
      - entity: sensor.hacs
    cards:
      - entities:
          - entity: input_select.scene
          - entity: input_boolean.climate_control
          - entity: input_boolean.aircon
        hours_to_show: 72
        refresh_interval: 0
        title: Control History
        type: history-graph
      - entities:
          - entity: sensor.warnings_numeric
          - entity: sensor.errors_numeric
        hours_to_show: 72
        refresh_interval: 0
        title: Warnings & Errors
        type: history-graph
      - entities:
          - entity: sensor.entryway_protect_battery_health_state
          - entity: sensor.living_room_protect_battery_health_state
          - entity: sensor.garage_protect_battery_health_state
          - entity: sensor.kitchen_multisensor_battery_level
          - entity: sensor.multisensor_battery_level
          - entity: sensor.switch1_battery_level
          - entity: sensor.switch2_battery_level
        hours_to_show: 72
        refresh_interval: 0
        title: Battery Levels
        type: history-graph
    path: system
    title: System
    visible:
      - user: 15ff7a86d4ae4d38a60003ad4064ff78
      - user: d678a59ca9604e2ba14c3ac3705ba943
