- platform: tod
  name: Rachel's sleep time
  unique_id: rachel_s_sleep_time
  after: "22:00"
  before: "7:00"
- platform: tod
  name: Dan's sleep time
  unique_id: dan_s_sleep_time
  after: "23:30"
  before: "7:00"
