- alias: Turn TV on if not already on
  description: "Required to turn the TV on from Home Assistant - sends a wake on lan magic packet"
  trigger:
    - platform: webostv.turn_on
      entity_id: media_player.tv
  action:
    - service: wake_on_lan.send_magic_packet
      data:
        mac: !secret tv_mac
# TODO: https://app.asana.com/0/1207020279479204/1207033183175582/f
# Maybe set up homekit here on zwave setup completion? Or maybe do this here:
# https://app.asana.com/0/1207020279479204/1207033183175579/f
