counter:
  errors:
    name: Errors
    restore: true
  warnings:
    name: Warnings
    restore: true

sensor:
  - platform: statistics
    name: Errors in the last hour
    unique_id: errors_in_the_last_hour
    entity_id: counter.errors
    state_characteristic: change
    keep_last_sample: true
    max_age:
      hours: 1
  - platform: statistics
    name: Warnings in the last hour
    unique_id: warnings_in_the_last_hour
    entity_id: counter.warnings
    state_characteristic: change
    keep_last_sample: true
    max_age:
      hours: 1

template:
  - sensor:
      - name: System issues in the last hour
        unique_id: system_issues_in_the_last_hour
        state: "{{ states('sensor.warnings_in_the_last_hour')|int(1) + states('sensor.errors_in_the_last_hour')|int(1) }}"
        state_class: total
        icon: mdi:home-alert
      - name: Device issues
        unique_id: device_issues
        state: "{{ states('sensor.unavailable_entities')|int(1) + states('sensor.frozen_entities')|int(1) }}"
        state_class: total
        icon: mdi:alert-circle
      - name: Unavailable entities
        unique_id: unavailable_entities
        state: >
          {% set entities = state_attr('group.unavailable_entities', 'entity_id') %}
          {{ entities|count if entities != none else none }}
        state_class: measurement
        unit_of_measurement: entities
        icon: mdi:alert-circle
      - name: Frozen entities
        unique_id: frozen_entities
        state: >
          {% set entities = state_attr('group.frozen_entities', 'entity_id') %}
          {{ entities|count if entities != none else none }}
        state_class: measurement
        unit_of_measurement: entities
        icon: mdi:help-circle
      - name: Low batteries
        unique_id: low_batteries
        state: >
          {% set entities = state_attr('group.low_batteries', 'entity_id') %}
          {% set unavailable = state_attr(this.entity_id, 'unavailable')|int(0) %}
          {{ (entities|count - unavailable) if entities != none else none }}
        attributes:
          unavailable: "{{ state_attr('group.low_batteries', 'entity_id')|reject('has_value')|list|count }}"
        state_class: measurement
        unit_of_measurement: devices
        icon: mdi:battery-low
      - name: Charging batteries
        unique_id: charging_batteries
        state: >
          {% set entities = state_attr('group.charging_batteries', 'entity_id') %}
          {{ entities|count if entities != none else none }}
        attributes:
          above_90: "{{ state_attr('group.charging_batteries', 'entity_id')|map('states')|map('float', 0)|select('ge', 90)|list|count }}"
          above_50: "{{ state_attr('group.charging_batteries', 'entity_id')|map('states')|map('float', 0)|select('ge', 50)|select('lt', 90)|list|count }}"
        state_class: measurement
        unit_of_measurement: devices
        icon: mdi:battery-charging

      - name: Nursery temperature sensor battery level
        unique_id: nursery_temperature_sensor_battery_level
        state: "{% from 'batteries.jinja' import temperature_sensor_battery %}{{ temperature_sensor_battery('nursery') }}"
        unit_of_measurement: "%"
        device_class: battery
        state_class: measurement
        availability: "{{ has_value('sensor.nursery_temperature_sensor_battery_state') }}"
      - name: Office temperature sensor battery level
        unique_id: office_temperature_sensor_battery_level
        state: "{% from 'batteries.jinja' import temperature_sensor_battery %}{{ temperature_sensor_battery('office') }}"
        unit_of_measurement: "%"
        device_class: battery
        state_class: measurement
        availability: "{{ has_value('sensor.office_temperature_sensor_battery_state') }}"
      - name: Dog bed area temperature sensor battery level
        unique_id: dog_bed_area_temperature_sensor_battery_level
        state: "{% from 'batteries.jinja' import temperature_sensor_battery %}{{ temperature_sensor_battery('dog_bed_area') }}"
        unit_of_measurement: "%"
        device_class: battery
        state_class: measurement
        availability: "{{ has_value('sensor.dog_bed_area_temperature_sensor_battery_state') }}"
      - name: Soil sensor entryway battery level
        unique_id: soil_sensor_entryway_battery_level
        state: "{% from 'batteries.jinja' import soil_sensor_battery %}{{ soil_sensor_battery('entryway') }}"
        unit_of_measurement: "%"
        device_class: battery
        state_class: measurement
        availability: "{{ has_value('sensor.soil_battery_voltage_entryway') }}"
      - name: Soil sensor guest suite battery level
        unique_id: soil_sensor_guest_suite_battery_level
        state: "{% from 'batteries.jinja' import soil_sensor_battery %}{{ soil_sensor_battery('guest_suite') }}"
        unit_of_measurement: "%"
        device_class: battery
        state_class: measurement
        availability: "{{ has_value('sensor.soil_battery_voltage_guest_suite') }}"
      - name: Soil sensor stairway battery level
        unique_id: soil_sensor_stairway_battery_level
        state: "{% from 'batteries.jinja' import soil_sensor_battery %}{{ soil_sensor_battery('stairway') }}"
        unit_of_measurement: "%"
        device_class: battery
        state_class: measurement
        availability: "{{ has_value('sensor.soil_battery_voltage_stairway') }}"
      - name: Soil sensor back deck battery level
        unique_id: soil_sensor_back_deck_battery_level
        state: "{% from 'batteries.jinja' import soil_sensor_battery %}{{ soil_sensor_battery('back_deck') }}"
        unit_of_measurement: "%"
        device_class: battery
        state_class: measurement
        availability: "{{ has_value('sensor.soil_battery_voltage_back_deck') }}"
      - name: Soil sensor living room battery level
        unique_id: soil_sensor_living_room_battery_level
        state: "{% from 'batteries.jinja' import soil_sensor_battery %}{{ soil_sensor_battery('living_room') }}"
        unit_of_measurement: "%"
        device_class: battery
        state_class: measurement
        availability: "{{ has_value('sensor.soil_battery_voltage_living_room') }}"
      - name: Soil sensor dining room battery level
        unique_id: soil_sensor_dining_room_battery_level
        state: "{% from 'batteries.jinja' import soil_sensor_battery %}{{ soil_sensor_battery('dining_room') }}"
        unit_of_measurement: "%"
        device_class: battery
        state_class: measurement
        availability: "{{ has_value('sensor.soil_battery_voltage_dining_room') }}"
      - name: Soil sensor bathroom battery level
        unique_id: soil_sensor_bathroom_battery_level
        state: "{% from 'batteries.jinja' import soil_sensor_battery %}{{ soil_sensor_battery('bathroom') }}"
        unit_of_measurement: "%"
        device_class: battery
        state_class: measurement
        availability: "{{ has_value('sensor.soil_battery_voltage_bathroom') }}"
      - name: Soil sensor office battery level
        unique_id: soil_sensor_office_battery_level
        state: "{% from 'batteries.jinja' import soil_sensor_battery %}{{ soil_sensor_battery('office') }}"
        unit_of_measurement: "%"
        device_class: battery
        state_class: measurement
        availability: "{{ has_value('sensor.soil_battery_voltage_office') }}"

command_line:
  sensor:
    name: Disabled entities
    unique_id: disabled_entities
    json_attributes:
      - entities
    value_template: "{{ value_json.entities | length }}"
    command: "jq '.data.entities |= map(select(.disabled_by? != null) | {entity_id: .entity_id}) | del(.data.deleted_entities) | flatten | .[3]' < .storage/core.entity_registry"
    scan_interval: 300

automation:
  - alias: Update device issue and battery groups
    id: update_device_issue_and_battery_groups
    description: Update device issue and battery groups
    mode: single
    max_exceeded: silent
    triggers:
      - trigger: event
        event_type: call_service
        event_data:
          domain: group
          service: reload
      - trigger: time_pattern
        minutes: "/5"
    actions:
      - action: group.set
        data:
          object_id: unavailable_entities
          entities: >
            {% set allowed_entities = [
              'sensor.power_meter_relative_self_consumption',
            ] + integration_entities('iBeacon Tracker') +
            integration_entities('netgear')|select('search', '_ssid$')|list
            %}
            {% set unknown_allowed_entities =
                [
                    states.sensor.extreme_forecast,
                ]
                |selectattr('state', 'eq', 'unknown')
                |map(attribute='entity_id')|list
            %}
            {% set long_delay_hours = 3 %}
            {% set long_unknown_allowed_entities =
                [
                  states.sensor.rachel_s_phone_detected_activity,
                  states.binary_sensor.rachel_s_phone_still,
                ]
                |selectattr('state', 'eq', 'unknown')
                |selectattr('last_changed', 'ge', (now().timestamp() - long_delay_hours*60*60)|as_datetime)
                |map(attribute='entity_id')|list
            %}
            {% set disabled_entities = state_attr('sensor.disabled_device_entities', 'entities')
                |regex_replace(find='\[|\]|\{|\}|\'entity_id\':', replace='')
                |map(attribute='entity_id')|list
            %}
            {% set delay_minutes = 5 %}
            {{ states
                |rejectattr('entity_id', 'in', allowed_entities + unknown_allowed_entities + long_unknown_allowed_entities + disabled_entities)
                |rejectattr('entity_id', 'has_value')
                |rejectattr('domain', 'in', ['button', 'event', 'group', 'image', 'select'])
                |rejectattr('last_changed', 'ge', (now().timestamp() - delay_minutes * 60)|as_datetime)
                |map(attribute='entity_id')|list
            }}
      - action: group.set
        data:
          object_id: frozen_entities
          entities: >
            {% set frozen_entities_10_minute_check_entities =
                [
                  states.sensor.outside_apparent_temperature,
                  states.sensor.bedroom_presence_sensor_esp_temperature,
                  states.sensor.kitchen_presence_sensor_esp_temperature,
                  states.sensor.nursery_presence_sensor_esp_temperature,
                  states.sensor.office_presence_sensor_esp_temperature,
                  states.sensor.smart_meter_real_power,
                  states.sensor.power_meter_power_load_consumed,
                ]
                |selectattr('entity_id', 'has_value')
                |selectattr('last_updated', 'le', (now().timestamp() - 10 * 60)|as_datetime)
                |map(attribute='entity_id')|list
            %}
            {% set frozen_entities_12_hour_check_entities =
                (
                  states.sensor|selectattr('entity_id', 'search', 'r_temperature$|feels_like|voltage$|last_seen')|list +
                  [
                    states.sensor.nursery_heater_uncalibrated_temperature,
                  ]
                )
                |selectattr('entity_id', 'has_value')
                |selectattr('last_updated', 'le', (now().timestamp() - 12 * 60 * 60)|as_datetime)
                |map(attribute='entity_id')|list
            %}
            {{ frozen_entities_10_minute_check_entities + frozen_entities_12_hour_check_entities }}
      - action: group.set
        data:
          object_id: low_batteries
          entities: >
            {% set low_battery_threshold = 25 %}
            {% set entities = states.sensor|selectattr('entity_id', 'search', 'battery_level$')|map(attribute='entity_id')|list|sort %}
            {% set battery_levels = entities|map('states')|map('float', 0)|list %}
            {{ zip(entities, battery_levels)|selectattr(1, '<=', low_battery_threshold)|map(attribute=0)|list }}
      - action: group.set
        data:
          object_id: charging_batteries
          entities: >
            {% set entities = states.sensor|selectattr('entity_id', 'search', 'charging_status$|battery_state$')|map(attribute='entity_id')|list|sort %}
            {% set status = entities|map('states')|list %}
            {% set entities = zip(entities, status)|selectattr(1, 'in', ['charging', 'Charging', 'full', 'Full'])|map(attribute=0)|list %}
            {{ entities|map('replace', 'battery_state', 'battery_level')|map('replace', 'charging_status', 'battery_level')|list }}
