template:
  - sensor:
      - name: Dry plants
        unique_id: dry_plants
        state: >
          {%- set sensors = [
             'binary_sensor.soil_moist_entryway',
             'binary_sensor.soil_moist_guest_suite',
             'binary_sensor.soil_moist_stairway',
             'binary_sensor.soil_moist_back_deck',
             'binary_sensor.soil_moist_living_room',
             'binary_sensor.soil_moist_dining_room',
             'binary_sensor.soil_moist_bathroom',
             'binary_sensor.soil_moist_office'
           ] -%}
           {{- (100 * sensors|select('is_state', 'off')|list|count / sensors|count)|round -}}
        unit_of_measurement: "%"
        icon: mdi:grass
        attributes:
          text: "{{ this.state|string + '% are dry'}}"
        availability: >
          {{
            has_value('binary_sensor.soil_moist_entryway') and
            has_value('binary_sensor.soil_moist_guest_suite') and
            has_value('binary_sensor.soil_moist_stairway') and
            has_value('binary_sensor.soil_moist_back_deck') and
            has_value('binary_sensor.soil_moist_living_room') and
            has_value('binary_sensor.soil_moist_dining_room') and
            has_value('binary_sensor.soil_moist_bathroom') and
            has_value('binary_sensor.soil_moist_office')
          }}

  - triggers:
      - trigger: state
        entity_id: sensor.dry_plants
        not_to:
          - "unknown"
          - "unavailable"
      - trigger: time_pattern
        minutes: 0
    binary_sensor:
      - name: Plants need watering
        unique_id: plants_need_watering
        state: >
          {{
            states('sensor.plants_last_watered')|as_datetime|as_local < now() - timedelta(days=5) or
            states('sensor.dry_plants')|int >= 50
          }}
        icon: mdi:watering-can
        availability: "{{ has_value('sensor.plants_last_watered') and has_value('sensor.dry_plants') }}"

  - triggers:
      - trigger: time_pattern
        minutes: 0
    sensor:
      - name: Front and back side days since watered
        unique_id: front_and_back_side_days_since_watered
        state: "{{ ((now() - states('sensor.front_and_back_side_last_watered')|as_datetime).total_seconds() / 60 / 60 / 24)|round(5) }}"
        unit_of_measurement: days
        state_class: total_increasing
        icon: mdi:clock
        availability: "{{ has_value('sensor.front_and_back_side_last_watered') }}"
      - name: Ferns days since watered
        unique_id: ferns_days_since_watered
        state: "{{ ((now() - states('sensor.ferns_last_watered')|as_datetime).total_seconds() / 60 / 60 / 24)|round(5) }}"
        unit_of_measurement: days
        state_class: total_increasing
        icon: mdi:clock
        availability: "{{ has_value('sensor.ferns_last_watered') }}"
      - name: Back fence days since watered
        unique_id: back_fence_days_since_watered
        state: "{{ ((now() - states('sensor.back_fence_last_watered')|as_datetime).total_seconds() / 60 / 60 / 24)|round(5) }}"
        unit_of_measurement: days
        state_class: total_increasing
        icon: mdi:clock
        availability: "{{ has_value('sensor.back_fence_last_watered') }}"
      - name: Vegetable garden days since watered
        unique_id: vegetable_garden_days_since_watered
        state: "{{ ((now() - states('sensor.vegetable_garden_last_watered')|as_datetime).total_seconds() / 60 / 60 / 24)|round(5) }}"
        unit_of_measurement: days
        state_class: total_increasing
        icon: mdi:clock
        availability: "{{ has_value('sensor.vegetable_garden_last_watered') }}"
      - name: Lawn days since watered
        unique_id: lawn_days_since_watered
        state: "{{ ((now() - states('sensor.lawn_last_watered')|as_datetime).total_seconds() / 60 / 60 / 24)|round(5) }}"
        unit_of_measurement: days
        state_class: total_increasing
        icon: mdi:clock
        availability: "{{ has_value('sensor.lawn_last_watered') }}"

  - triggers:
      - trigger: state
        entity_id: sensor.dry_plants
        to: "0"
        not_from:
          - "0"
          - "unknown"
          - "unavaiable"
          - none
    sensor:
      - name: Plants last watered
        unique_id: plants_last_watered
        state: "{{ now() }}"
        device_class: timestamp
        icon: mdi:clock

binary_sensor:
  - platform: threshold
    name: Soil moist entryway
    entity_id: sensor.soil_moisture_entryway
    upper: 30
    hysteresis: 5
    device_class: moisture
  - platform: threshold
    name: Soil moist guest suite
    entity_id: sensor.soil_moisture_guest_suite
    upper: 30
    hysteresis: 5
    device_class: moisture
  - platform: threshold
    name: Soil moist stairway
    entity_id: sensor.soil_moisture_stairway
    upper: 30
    hysteresis: 5
    device_class: moisture
  - platform: threshold
    name: Soil moist back deck
    entity_id: sensor.soil_moisture_back_deck
    upper: 30
    hysteresis: 5
    device_class: moisture
  - platform: threshold
    name: Soil moist living room
    entity_id: sensor.soil_moisture_living_room
    upper: 30
    hysteresis: 5
    device_class: moisture
  - platform: threshold
    name: Soil moist dining room
    entity_id: sensor.soil_moisture_dining_room
    upper: 30
    hysteresis: 5
    device_class: moisture
  - platform: threshold
    name: Soil moist bathroom
    entity_id: sensor.soil_moisture_bathroom
    upper: 30
    hysteresis: 5
    device_class: moisture
  - platform: threshold
    name: Soil moist office
    entity_id: sensor.soil_moisture_office
    upper: 30
    hysteresis: 5
    device_class: moisture
