title: Smart Nest
views:
  - badges: []
    cards:
      - entities:
          - entity: input_select.scene
          - entity: input_boolean.climate_control
          - entity: input_boolean.aircon
          - entity: input_boolean.pets_home_alone
          - entity: lock.door_lock
        show_header_toggle: false
        title: Control
        type: entities
        state_color: true
      - card:
          entities:
            - entity: input_number.high_temperature_trigger
            - entity: input_number.low_temperature_trigger
          show_header_toggle: false
          title: Climate Control Triggers
          type: entities
          state_color: true
        conditions:
          - entity: input_boolean.climate_control
            state: "on"
          - entity: binary_sensor.display_day_card
            state: "on"
        type: conditional
      - card:
          entities:
            - entity: input_number.sleep_high_temperature_trigger
            - entity: input_number.sleep_low_temperature_trigger
          show_header_toggle: false
          title: Climate Control Triggers
          type: entities
          state_color: true
        conditions:
          - entity: input_boolean.climate_control
            state: "on"
          - entity: binary_sensor.display_day_card
            state: "off"
        type: conditional
      - card:
          entities:
            - entity: input_number.cooling_target_temperature
            - entity: input_number.heating_target_temperature
          show_header_toggle: false
          title: Aircon Temperatures
          type: entities
          state_color: true
        conditions:
          - entity: sensor.any_climate_control
            state: "True"
          - entity: binary_sensor.display_day_card
            state: "on"
        type: conditional
      - card:
          entities:
            - entity: input_number.sleep_cooling_target_temperature
            - entity: input_number.sleep_heating_target_temperature
          show_header_toggle: false
          title: Aircon Temperatures
          type: entities
          state_color: true
        conditions:
          - entity: sensor.any_climate_control
            state: "True"
          - entity: binary_sensor.display_day_card
            state: "off"
        type: conditional
      - card:
          entities:
            - entity: sensor.apparent_inside_temperature_numeric
              name: Inside
              icon: mdi:home-thermometer
            - entity: sensor.apparent_outside_temperature
              name: Outside
              icon: mdi:sun-thermometer
          show_name: true
          type: glance
          state_color: true
        conditions: []
        type: conditional
      - cards:
          - entities:
              - entity: group.all_lights
              - entity: group.entryway_lights
              - entity: group.kitchen_lights
              - entity: group.tv_lights
              - entity: group.dining_lights
              - entity: light.hall
              - entity: light.bedroom
              - entity: light.office
            show_icon: true
            show_name: true
            show_state: true
            title: Lights
            type: glance
            state_color: true
          - type: entities
            entities:
              - entity: input_boolean.custom_lighting
            show_header_toggle: false
            state_color: true
          - content: >-
              Enabling **custom lighting** will prevent automatic adjustments.
              This is most useful at night when you want to override automatic
              circadian rhythm dimming and colour adjustments.
            type: markdown
        type: vertical-stack
      - entity: media_player.tv
        type: media-control
      - cards:
          - entities:
              - entity: input_datetime.morning_time
              - entity: input_datetime.bed_time
            show_header_toggle: false
            title: Times
            type: entities
            state_color: true
          - content: >-
              Specify the time for which the ***Morning*** scene and pre-sleep
              climate control will trigger. More information in the
              **Instructions** tab.
            type: markdown
        type: vertical-stack
      - entities:
          - entity: sensor.apparent_inside_temperature_numeric
          - entity: sensor.smartweather_feels_like
          - entity: climate.living_room
          - entity: climate.dining_room
          - entity: climate.bedroom
          - entity: sensor.office_multisensor_temperature
        hours_to_show: 24
        refresh_interval: 0
        title: Temperatures
        type: history-graph
      - cards:
          - type: glance
            entities:
              - entity: climate.living_room
              - entity: climate.dining_room
              - entity: climate.bedroom
            show_name: true
            show_icon: true
            show_state: true
            state_color: true
            title: Manual Aircon Control
          - content: >-
              To manually control the individual airconditioning units above,
              make sure to disable automatic climate control beforehand.
            type: markdown
        type: vertical-stack
      - aspect_ratio: "2"
        dark_mode: true
        default_zoom: 12
        auto_fit: true
        entities:
          - device_tracker.daniels_phone
          - device_tracker.rachel_s_phone_2
        hours_to_show: 1
        type: map
    path: default_view
    title: Control & Status
  - title: Instructions
    path: instructions
    icon: ""
    badges: []
    cards:
      - content: >-
          **Lighting** and **climate settings** (if enabled) are automatically
          adjusted between different scenes. You can also manually select a
          preferred scene here, or tell Siri/Google:

          - **"lights on"** or **"lights off"** for the *Night* and *Day* scenes

          - **"lights on bright"** for the *Bright* scene

          - **"sleep time"** for the *Sleep* scene


          **Automatic climate control** will control all aircon units based on
          the current scene and the temperature throughout the house as well as
          outside. If the pets are home alone (or are going to be soon), you can
          manually specify this or wait for their movement to be detected to
          trigger climate control. **Aircon** can also be manually turned on and
          off. These settings can be controlled by telling Siri/Google:

          - **"climate control on"** or **"climate control off"**

          - **"aircon on"** or **"aircon off"**


          Each **scene** has a particular purpose:

          - ***Morning*** is designed to trigger before anyone wakes up (at the
          time specified in the settings here), providing dim kitchen lighting
          plus climate control to the whole house (rather than just the
          bedroom). Thus when anyone does get up it is to a comfortable
          temperature and sufficient lighting.

          - ***Day*** is triggered when ambient lighting in the house is
          sufficient, and thus turns off all lighting.

          - ***Night*** is triggered when there is insufficent lighting, turning
          on the main lights in the house. The brightness and colour temperature
          of all lighting adjusts as the night goes on, getting dimmer and
          warmer so as to reduce the impact to your circadian rhythm.

          - ***Sleep*** turns off all lighting in the house. If climate control
          is enabled, only the bedroom is monitored and controlled. This scene
          has to be manually triggered.

          - ***TV*** dims the lights for a nice viewing experience,
          automatically triggered when the TV is playing at Night.

          - ***Bright*** turns all lights on at full brightness and has to be
          manually triggered.

          - ***Away (Night/Day)*** turns off all lights (except one obvious one
          at night for security purposes) and disables climate control.
          Automatically triggered when both of us have left the house.


          The **buttons** in the kitchen and bedroom will essentially toggle
          lighting when clicked, intelligently changing the scene based on the
          current conditions. The bedroom button also allows you to first switch
          from ***Night*** to ***Sleep*** while keeping the bedroom light on,
          then when clicked again it will turn the bedroom light off (properly
          entering ***Sleep***). Holding either button for a few seconds will
          toggle the aircon.


          Lighting in the entryway, kitchen, office and bedroom will
          automatically brighten when someone enters, and dim shortly after they
          leave (depending on scene settings). Automatic bedroom lighting is
          disabled as soon as the ***Sleep*** scene starts, only enabling again
          when the bedroom **button** is clicked or after luminance levels peak
          (i.e. after blinds are first opened in the morning).


          Only the bedroom aircon will be controlled after the specified bed
          time, regardless of the scene.


          In order to use Siri, you will need to add the following Siri
          shortcuts to your device: [Sleep
          Time](https://www.icloud.com/shortcuts/1c19b6e78b3c492d867cb63305bbfaa9),
          [Lights On
          Bright](https://www.icloud.com/shortcuts/d4bf116ae08c4d8a8290827f5c126010),
          [Lights
          On](https://www.icloud.com/shortcuts/7cb15602d0974ce1a897f422901acafd),
          [Lights
          Off](https://www.icloud.com/shortcuts/e424f0052a014954a71452d01a122167),
          [Aircon
          On](https://www.icloud.com/shortcuts/dab4081c117e4b8c8c0f3f5bff5b9a34),
          [Aircon
          Off](https://www.icloud.com/shortcuts/87e1dda3345f41f391c3030d09621655),
          [Enable Climate
          Control](https://www.icloud.com/shortcuts/19419fdeecea43b6914a420701fb7b35),
          [Disable Climate
          Control](https://www.icloud.com/shortcuts/f322c4c33abd45f5b2dd82281219b706),
          [Lock The
          Door](https://www.icloud.com/shortcuts/0e14667cabbd436aa2704a7fd31359b1),
          [Unlock The
          Door](https://www.icloud.com/shortcuts/27f357e7fdbd4293927259d4d4326b0d),
          [TV
          On](https://www.icloud.com/shortcuts/72c845af76b24ff28a965e34a07f7b6f).

          In order to use Google, you will need to connect your Google Assistant
          to IFTTT and add applets with webhooks to Home Assistant corresponding
          to each command.
        type: markdown
  - path: lights
    title: Settings
    badges: []
    cards:
      - cards:
          - entities:
              - entity: input_number.initial_circadian_brightness
              - entity: input_number.initial_circadian_kelvin
              - entity: input_number.final_circadian_brightness
              - entity: input_number.final_circadian_kelvin
              - entity: input_number.circadian_initial_sunset_offset
              - entity: input_datetime.circadian_end_time
            title: Circadian Rhythm
            type: entities
            state_color: false
          - content: >-
              Lighting at night will gradually transition between the intial and
              final brightness and colour values specified here.


              Initial circadian settings occur after sunset (specified in hours
              by *initial sunset offset*) and reaches the final values at *end
              time*.
            type: markdown
        type: vertical-stack
      - cards:
          - content: >-
              Values here specify the *brightness* and colour temperature of
              lighting in different scenes. Colour temperature ranges from warm
              white (2000 *kelvin*) to cold white (4500 *kelvin*).


              *Motion* indicates the value is specific to when the room is
              occupied (otherwise defaulting to the normal values specified, the
              current circadian value, off, or maximum - depending on the
              scene).


              *Vacating delay* specifies how long the light will wait after
              someone leaves the room before reverting to its previous state.


              If a *transition period* is available the light will smoothly
              change over that period to or from the motion brightness and
              kelvin specified or implied.
            type: markdown
          - entities:
              - entity: input_number.night_motion_brightness
              - entity: input_number.night_motion_kelvin
              - entity: input_number.night_transition_period
              - entity: input_number.night_vacating_delay
            title: Night
            type: entities
          - entities:
              - entity: input_number.tv_brightness
              - entity: input_number.tv_kelvin
              - entity: input_number.tv_motion_brightness
              - entity: input_number.tv_transition_period
              - entity: input_number.tv_vacating_delay
            title: TV
            type: entities
          - entities:
              - entity: input_number.sleep_motion_brightness
              - entity: input_number.sleep_motion_kelvin
              - entity: input_number.sleep_transition_period
              - entity: input_number.sleep_vacating_delay
            title: Sleep
            type: entities
          - entities:
              - entity: input_number.morning_brightness
              - entity: input_number.morning_kelvin
              - entity: input_number.morning_vacating_delay
            title: Morning
            type: entities
        type: vertical-stack
      - entities:
          - entity: input_number.office_vacating_delay
          - entity: input_number.bedroom_vacating_delay
        title: Room Vacating Delays
        type: entities
      - type: entities
        entities:
          - entity: input_number.aircon_door_check_delay
            icon: mdi:timer
        title: Aircon Door Check Delay
  - path: system
    title: System
    visible:
      - user: 15ff7a86d4ae4d38a60003ad4064ff78
      - user: d678a59ca9604e2ba14c3ac3705ba943
    badges:
      - type: entity-filter
        state_filter:
          - "on"
        entities:
          - entity: update.home_assistant_core_update
            name: Core
          - entity: update.home_assistant_supervisor_update
            name: Supervisor
          - entity: update.home_assistant_operating_system_update
            name: Operating System
      - type: entity-filter
        state_filter:
          - operator: ">"
            value: 0
        entities:
          - entity: sensor.hacs
    cards:
      - entities:
          - entity: input_select.scene
          - entity: input_boolean.climate_control
          - entity: input_boolean.aircon
        hours_to_show: 36
        refresh_interval: 0
        title: Control History
        type: history-graph
      - type: entities
        entities:
          - input_boolean.development_mode
      - entities:
          - entity: sensor.warnings_numeric
          - entity: sensor.errors_numeric
        hours_to_show: 72
        refresh_interval: 0
        title: Warnings & Errors
        type: history-graph
      - entities:
          - entity: sensor.doorbell_battery_level
          - entity: sensor.door_lock_battery_level
          - entity: sensor.entryway_multisensor_battery_level
          - entity: sensor.kitchen_multisensor_battery_level
          - entity: sensor.office_multisensor_battery_level
          - entity: sensor.bedroom_multisensor_battery_level
          - entity: sensor.kitchen_button_battery_level
          - entity: sensor.bedroom_button_battery_level
          - entity: sensor.nest_protect_entryway_battery_level
          - entity: sensor.nest_protect_living_room_battery_level
          - entity: sensor.nest_protect_garage_battery_level
        hours_to_show: 72
        refresh_interval: 0
        title: Battery Levels
        type: history-graph
